### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by yyx990803** [pearofducks/gitbook-plugin-theme-vuejs#3]
First of all - thanks a lot for making this theme, we've been using it in most gitbook-powered Vue documentations and it's been working really well. So far all those usages are pointing directly to this repo, it would probably be nicer if we publish this on npm so it can be versioned.

**Comment by pearofducks** [comment]
I completely agree - sorry for not seeing this issue - somehow GitHub swallowed the notification.

I saw vuejs forked this - which probably means Vue documentation will inherit from the forked repo? Do you plan to just pull upstream changes then?* As published updates on npm probably won't be relevant for Vue then?

*Alternatively we could simply transfer ownership to the vuejs group, which seems far simpler to me and maybe a better long term solution

**Comment by yyx990803** [comment]
@pearofducks thanks, I have published the fork to npm and the docs are already using that version - but thanks a lot for working on this!
